//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWordDictionary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonDetail
    {
        public int LessonDetailID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> LessonID { get; set; }
        public Nullable<int> WordID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual Word Word { get; set; }
    }
}
